### ISSUE TITLE
Unknown relocation type fix

### ISSUE THREAD

**Issue by hstocks** [push0ebp/sig-database#2]
Hey - I saw you had issues with generating certain .pat files.
To fix this you can add the "-rXX:0:0" flag to your command, where XX is the unknown relocation type number. 

So if you were running `./pelf libc.a libc.pat` and got the following error:
> Fatal [libc.a] (init-first.o): Unknown relocation type 42 (section#=3, offset in section=0x1b9d000000000).

Your new command would be `./pelf libc.a -r42:0:0 libc.pat`. You may have to do this several times before it works, but you can just add the same flag multiple times if so.

Hope this helps.

**Comment by push0ebp** [comment]
Oh Thanks much.
Then. Following your suggestion, I can generate pat file such powerpc, mips architecture?

**Comment by hstocks** [comment]
Yes, you should be able to.

**Comment by push0ebp** [comment]
Thx, I will reflect it next commit.

**Comment by push0ebp** [comment]
thank you for your contribution.
