### ISSUE TITLE
Question: generation script

### ISSUE THREAD

**Issue by oliveriandrea** [push0ebp/sig-database#3]
Hi, do you use a script in order to download all the libc version from repositories and generate signatures or do it by hand? If you use a script can you post it, please? :)

**Comment by push0ebp** [comment]
make a repository public

GitHub - push0ebp/ALLirt - [https://github.com/push0ebp/ALLirt](https://github.com/push0ebp/ALLirt)

Thank you

**Comment by Karaulov** [comment]
@push0ebp possible to get signatures for old visual studio 8.0 ? (v80, msvcr80.dll etc)
