### ISSUE TITLE
have ever faced “Couldn't find 'pelf.rtb' file” when use ./pelf 

### ISSUE THREAD

**Issue by summerban** [push0ebp/sig-database#5]
Hi, I use flair 6.3 to generate sig
but I faced  a question
Couldn't find 'pelf.rtb' file

press enter to exit.

and i really have pelf.rtb in this folder
dumpsig  libsndfile_elf.pat  pcf  pelf  pelf.rtb  plb  pmacho  pomf166  ppsx  ptmobj  sigmake  zipsig

could you please do me a favor to send me your's flair ，thank you very much

**Comment by push0ebp** [comment]
Hi, I guess your flair is something wrong. your version of flair older than released version.
I don't know this error exactly. sorry I can't help you well.
